# docker-compose.yml
version: '2'

services:
    db:
        image: mysql
        ports:
            - 3310:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_DATABASE: cofidur
            MYSQL_USER: cofidur_user
            MYSQL_PASSWORD: cofidur_user
            MYSQL_ROOT_PASSWORD: root
    php:
        build: php7-fpm
        ports:
            - 9000:9000
        links:
            - db:mysqldb
        volumes:
            - ./symfony:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
    nginx:
        build: nginx
        ports:
            - 85:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
